version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: mypass1.
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

# Uncomment and modify the following section according to your application requirements
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mssql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=travel
#      SPRING_DATASOURCE_USERNAME: sa
#      SPRING_DATASOURCE_PASSWORD: YourPasswordHere

volumes:
  mssql-data:
    driver: local
